[package]
name = "sylan"
version = "0.2.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"

[[bin]]
name = "sylan_server"
path = "src/server.rs"

[[bin]]
name = "sylan_client"
path = "src/client.rs"

[dependencies]
tar = "0.4.29"
